apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-service
  name: inventory-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 30306
    targetPort: 8080
  selector:
    io.kompose.service: inventory-service
status:
  loadBalancer: {}
